name: Execute premerge workflow
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run firefox tests
      uses: .github/workflows/execute_playwright_suite.yml
      with: 
        browser: firefox
        logLevel: INFO
    - name: Run chrome tests
      uses: .github/workflows/execute_playwright_suite.yml
      with: 
          browser: chrome
          logLevel: INFO
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: behavex-chrome-html-report
        path: output/

