name: Trigger behave suite
on:
  workflow_dispatch:
    inputs:
        logLevel:
            description: 'Log level'
            required: true
            default: 'INFO'
            type: choice
            options:
            - INFO
            - WARNING
            - DEBUG
        browser:
            description: 'Target browser'
            required: true
            default: 'chrome'
            type: choice
            options:
            - chrome
            - chromium
            - firefox
    
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run chrome tests
      run: behavex -D browser=$BROWSER --logging-level $LEVEL
      env:
        BROWSER: ${{ inputs.browser }}
        LEVEL: ${{ inputs.logLevel }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: behavex-$BROWSER-html-report
        path: output/
      env:
        BROWSER: ${{ inputs.browser }}
